spring:
  redis:
    host: ${csm.platform.twincache.host}
    username: ${csm.platform.twincache.username}
    password: ${csm.platform.twincache.password}
    client-type: jedis
  main:
    lazy-initialization: true

management:
  endpoints:
    enabled-by-default: false

csm:
  platform:
    metrics:
      enabled: false
    api:
      # API Base Path for OpenAPI-generated controllers.
      # Might conflict with the SpringBoot context path, hence leaving it at the root
      base-path: /
      base-url: "http://fake_url:8080"
      version: latest
    id-generator:
      type: hashid
    event-publisher:
      type: in_process
    images:
      scenario-fetch-parameters: cosmo-tech/fetch-scenario-parameters
      send-datawarehouse: not-implemented
      scenario-data-upload: not-implemented
    containers: []
    registries:
      core: coreregistry.svc.cluster.local:5000
      solutions: solutionsregistry.svc.cluster.local:5000
    upload:
      authorized-mime-types:
        workspaces:
          - application/zip
          - application/xml
          - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
          - application/x-tika-ooxml
          - text/csv
          - text/plain
          - text/x-yaml
          - application/json
        handlers:
          - application/zip
          - application/x-sh
          - application/json
          - text/x-python
          - text/plain
          - text/x-yaml
    authorization:
      tenant-id-jwt-claim: "iss"
      # Note that the way @Value works in Spring does not make it possible to inject this sole YAML list.
      # Use CsmPlatformProperties instead !
      allowed-tenants: ["test"]
    vendor: cosmotech
    argo:
      base-uri: "https://argo-server.argo.svc.cluster.local:2746"
      workflows:
        namespace: phoenix
        node-pool-label: ""
        service-account-name: workflowcsmv2
        storage-class: null
        access-modes:
          # Any in the following list: ReadWriteOnce, ReadOnlyMany, ReadWriteMany, ReadWriteOncePod (K8s 1.22+)
          - ReadWriteOnce
        requests:
          storage: 1Gi
    twincache:
      host: "localhost"
      port: "6379"
      username: "default"
      password: "my-wonderful-password"
      scenario:
        default-page-size: 20
    rbac:
      enabled: true
    identityProvider:
      code: cosmotech
      # Use to overwrite openAPI configuration
      authorizationUrl: "http://iam.svc.cluster.local/oauth2/default/v1/authorize"
      tokenUrl: "http://iam.svc.cluster.local/oauth2/default/v1/token"
      defaultScopes:
        openid: "OpenId Scope"
      containerScopes:
        csm.scenario.read: "Read access to scenarios"
      # Here you can set custom user and admin groups
      # - adminGroup will have same rights that Organization.Admin
      # - userGroup will have same rights that Organization.User
      # - viewerGroup will have same rights that Organization.Viewer
      userGroup: "SAMS-ADMINACCESS-DEV"
      viewerGroup: "SAMS-USERACCESS-DEV"



