{{- $baseConfig := include "cosmotech-api.baseConfig" . | fromYaml -}}
{{- $mergedConfig := mustMergeOverwrite (dict) .Values.config $baseConfig -}}
{{- $mergedConfigWithoutPlatformSensitiveInfo := omit $mergedConfig "csm" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "cosmotech-api.fullname" . }}
data:
  application.yml: |-
    {{- toYaml $mergedConfigWithoutPlatformSensitiveInfo | nindent 4 }}
