{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cosmotech-api.fullname" . }}-deny-all
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cosmotech-api.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
    "com.cosmotech/description": "DENY all traffic from other namespaces"
spec:
  policyTypes:
    - Ingress
  podSelector: {}
  ingress: []
{{- end }}

---
{{- if .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cosmotech-api.fullname" . }}-allow-whitelisted
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "cosmotech-api.defaultNetworkPolicy" . | indent 6}}
  ingress:
  - {}
{{- end }}