{{- if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-api.fullname" . }}-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cosmotech-api.imagePullSecret" . }}
{{- end }}
