{{- if .Values.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-api.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cosmotech-api.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cosmotech-api.imagePullSecret" . }}
{{- end }}

---
{{- if .Values.argo.imageCredentials.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-api.fullname" . }}-workflow-registry
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cosmotech-api.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cosmotech-api.argo.imagePullSecret" . }}
{{- end }}
