{{- if .Values.argo.storage.class.install -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "cosmotech-api.fullname" . }}-{{ .Release.Namespace }}
  labels:
  {{- include "cosmotech-api.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
provisioner: {{ .Values.argo.storage.class.provisioner }}
mountOptions:
  {{- range .Values.argo.storage.class.mountOptions }}
  - {{ . }}
  {{- end }}
parameters:
  {{- with .Values.argo.storage.class.parameters }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
