kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: phoenix-azurefile-{{ .Values.api.version }}
provisioner: {{ .Values.argo.storage.class.provisioner }}
mountOptions:
  {{- range .Values.argo.storage.class.mountOptions }}
  - {{ . }}
  {{- end }}
parameters:
  {{- with .Values.argo.storage.class.parameters }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
