{{- if .Values.argo.controller.persistence.archive }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-argo-postgresql-secret"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  postgresql.username: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresql.password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
