replicaCount: 1

image:
  repository: localhost:5000/cosmotech-api
  pullPolicy: Always

api:
  # A Cosmo Tech Helm Release (e.g., latest, vX) is linked to an API Version;
  # so it must define its own path rules here.
  # This corresponds to the path under which this service is exposed, if behind a reverse proxy or
  # load balancer
  servletContextPath: /cosmotech-api
  # Examples: latest, v1, v2
  version: latest

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: localhost

config:
  logging:
    level:
      com:
        azure: INFO
        cosmotech: DEBUG
  csm:
    platform:
      azure:
        cosmos:
          key: "changeme"
          uri: "changeme"

