# Copyright (c) Cosmo Tech.
# Licensed under the MIT license.

#
# Default values for cosmotech-api.
#

# -- number of pods replicas
replicaCount: 1

image:
  # -- container image to use for deployment
  repository: ghcr.io/cosmo-tech/cosmotech-api
  # -- [policy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) for pulling the image
  pullPolicy: Always
  # -- container image tag. Defaults to the Chart `appVersion` if empty or missing
  tag: ""

#imagePullSecrets: []

# Set image pull secrets (in case you're using a private container registry).
imageCredentials:
  # -- container registry to use for pulling the Deployment image. Useful if you are using a private registry
  registry: ""
  # -- username for the container registry to use for pulling the Deployment image. Useful if you are using a private registry
  username: ""
  # -- password for registry to use for pulling the Deployment image. Useful if you are using a private registry
  password: ""

# -- value overriding the name of the Chart. Defaults to the Chart name.
# Truncated at 63 chars because some Kubernetes name fields are limited to this.
nameOverride: ""
# -- value overriding the full name of the Chart. If not set, the value is computed from `nameOverride`.
# Truncated at 63 chars because some Kubernetes name fields are limited to this.
fullnameOverride: ""

serviceAccount:
  # -- whether a service account should be created
  create: true
  # -- annotations to add to the service account
  annotations: {}
  # -- the name of the service account to use.
  # If not set and `serviceAccount.create` is `true`, a name is generated using the `fullname` template
  name: ""

# -- Deployment strategy
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    # -- maximum number of Pods that can be created over the desired number of Pods
    maxSurge: 1
    # -- maximum number of Pods that can be unavailable during the update process
    maxUnavailable: 50%

# -- annotations to set the Deployment pod
podAnnotations: {}

# -- the pod security context, i.e. applicable to all containers part of the pod
podSecurityContext:
  runAsNonRoot: true

# -- the security context at the pod container level
securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- service type. See [this page](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) for the possible values
  type: ClusterIP
  # -- service port
  port: 8080
  # -- service management port
  managementPort: 8081

networkPolicy:
  enabled: true

api:
  # A Cosmo Tech Helm Release (e.g., latest, vX) is linked to an API Version;
  # so it must define its own path rules here.
  # This corresponds to the path under which this service is exposed, if behind a reverse proxy or
  # load balancer
  servletContextPath: /
  # Examples: latest, v1, v2
  version: latest
  # Whether or not the API is multi-tenant and should expose the tenant in the URL
  multiTenant: true
  # Configure probes failure thresholds to higher values if you are in debug mode to avoid pod restart
  probes:
    startup:
      initialDelaySeconds: 60
      failureThreshold: 50
    liveness:
      timeoutSeconds: 10
      failureThreshold: 5
    readiness:
      timeoutSeconds: 10
      failureThreshold: 5
  serviceMonitor:
    enabled: true
    namespace: "cosmotech-monitoring"
    additionalLabels: {}
  tlsTruststore:
    enabled: false
    secretName: ""
    secretKey: ""
    fileName: ""
    type: "pem"
    jksPassword: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: Prefix # For Kubernetes >= 1.19.0
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- resources limits and requests for the pod placement
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

persistence:
  # -- Enable the data storage persistence
  enabled: true
  # -- PVC storage request for the data volume
  size: 8Gi
  # -- PVC storage class for the data volume, currently requires a ReadWriteMany capability
  storageClass: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

# -- default behavior is a pod anti-affinity, which prevents pods from co-locating on a same node
affinity: {}

argo:
  # Set image pull secrets for Argo Workflows (in case you're using a private container registry).
  imageCredentials:
    # -- container registry to use for pulling the Workflow images. Useful if you are using a private registry
    registry: ""
    # -- username for the container registry to use for pulling the Workflow images. Useful if you are using a private registry
    username: ""
    # -- password for registry to use for pulling the Workflow images. Useful if you are using a private registry
    password: ""

config:
  csm:
    platform:
      twincache:
        host: redis.host.changeme
        password: changeme
        port: 6379
        username: default
        tls:
          enabled: false
          bundle: ""
      argo:
        base-uri: "http://argo-server:2746"
        workflows:
          # -- Name of the storage class for Workflows volumes.
          # Useful if you want to use a different storage class managed externally
          storage-class: null
          access-modes:
            # -- Any in the following list: ReadWriteOnce, ReadOnlyMany, ReadWriteMany, ReadWriteOncePod (K8s 1.22+).
            - ReadWriteOnce
          requests:
            # File storage minimal claim is 100Gi for Premium classes
            storage: 100Gi
      authorization:
        allowed-tenants: []
      identityProvider:
        code: keycloak
        authorizationUrl: "changeme"
        tokenUrl: "changeme"
        defaultScopes:
          openid: "OpenId Scope"
        containerScopes:
          changeme: "changeme"
        serverBaseUrl: "changeme"
        audience: "changeme"
        identity:
          clientId: "changeme"
          clientSecret: "changeme"
          tenantId: "changeme"
        tls:
          enabled: false
          bundle: "changeme"
      internalResultServices:
        enabled: false
        storage:
          host: "localhost"
          port: 5432
          reader:
            username: "changeme"
            password: "changeme"
          writer:
            username: "changeme"
            password: "changeme"
          admin:
            username: "changeme"
            password: "changeme"
        eventBus:
          enabled: true
          tls:
            enabled: false
            bundle: ""
          host: "localhost"
          port: 5672
          listener:
            username: "changeme"
            password: "changeme"
          sender:
            username: "changeme"
            password: "changeme"
