replicaCount: 2

# Set image pull secrets (in case you're using a private container registry).
#imageCredentials:
#  registry: csmphoenix.azurecr.io
#  # az acr credential show -n csmphoenix --query="username" -o tsv
#  username: changeme
#  # az acr credential show -n csmphoenix --query="passwords[0].value" -o tsv
#  password: "changeme"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: api.azure.cosmo-platform.com
  tls:
    - secretName: tls-secret
      hosts:
        - api.azure.cosmo-platform.com

resources:
  # Recommended in production environments
  limits:
    #   cpu: 100m
    memory: 2048Mi
  requests:
    #   cpu: 100m
    memory: 1024Mi

#argo:
#  imageCredentials:
#    registry: "csmenginesdev.azurecr.io"
#    # az acr credential show -n csmengines --query="username" -o tsv
#    username: "changeme"
#    # az acr credential show -n csmengines --query="passwords[0].value" -o tsv
#    password: "changeme"

argo:
  storage:
    class:
      install: true

config:
  csm:
    platform:
      argo:
        workflows:
          storage-class: null
          access-modes:
            - ReadWriteMany
          requests:
            # Azure file storage minimal claim is 100Gi for Premium classes
            storage: 100Gi
      azure:
        credentials:
          # TODO Breaking change: Move deprecated tenantId, clientId and clientSecret under the new 'core' field
          tenantId: "changeme"
          clientId: "changeme"
          clientSecret: "changeme"
          customer:
            tenantId: "changeme"
            clientId: "changeme"
            clientSecret: "changeme"
        dataWarehouseCluster:
          baseUri: "https://changeme.kusto.windows.net"
          options:
            ingestionUri: "https://changeme.kusto.windows.net"
        eventBus:
          baseUri: "amqps://changeme.servicebus.windows.net"
        storage:
          account-name: "changeme"
          account-key: "changeme"
      containerRegistry:
        provider: azure
        registryUrl: "https://changeme.azurecr.io"
