image:
  repository: localhost:5000/cosmotech-api
  pullPolicy: Always
  tag: "latest"

api:
  # A Cosmo Tech Helm Release (e.g., latest, vX) is linked to an API Version;
  # so it must define its own path rules here.
  # This corresponds to the path under which this service is exposed, if behind a reverse proxy or
  # load balancer
  servletContextPath: /cosmotech-api

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.org/client-max-body-size: "0"
  hosts:
    - host: localhost

config:
  logging:
    level:
      com:
        azure: INFO
        cosmotech: DEBUG
  csm:
    platform:
      azure:
        credentials:
          core:
            tenantId: "changeme"
            clientId: "changeme"
            clientSecret: "changeme"
        cosmos:
          key: "changeme"
          uri: "https://changeme.documents.azure.com:443/"
        dataWarehouseCluster:
          baseUri: "https://changeme.kusto.windows.net"
          options:
            ingestionUri: "https://changeme.kusto.windows.net"
        eventBus:
          baseUri: "amqps://changeme.servicebus.windows.net"
        storage:
          account-name: "changeme"
          account-key: "changeme"
        containerRegistries:
          solutions: "localhost:5000"
