# Spring boot okta starter will read these lines and will inject okta's autoconfigured beans

okta:
  oauth2:
    issuer: "${csm.platform.identityProvider.serverBaseUrl}/oauth2/default"
    clientId: ${csm.platform.identityProvider.identity.clientId}
    clientSecret: ${csm.platform.identityProvider.identity.clientSecret}
    audience: ${csm.platform.identityProvider.audience}

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "${csm.platform.identityProvider.serverBaseUrl}/oauth2/default"
          jwk-set-uri: "${csm.platform.identityProvider.serverBaseUrl}/oauth2/default/v1/keys"
          audiences:
            - ${csm.platform.identityProvider.audience}

csm:
  platform:
    authorization:
      principal-jwt-claim: "sub"
      application-id-jwt-claim: "cid"
      mail-jwt-claim: "sub"
      roles-jwt-claim: "groups"
      allowed-tenants: ${csm.platform.authorization.allowedTenants}
