logging:
  level:
    org.keycloak: WARN

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "${csm.platform.identityProvider.serverBaseUrl}/realms/${csm.platform.identityProvider.identity.tenantId}"
          jwk-set-uri: "${csm.platform.identityProvider.serverBaseUrl}/realms/${csm.platform.identityProvider.identity.tenantId}/protocol/openid-connect/certs"
          audiences:
            - ${csm.platform.identityProvider.audience}

csm:
  platform:
    authorization:
      mail-jwt-claim: "email"
      roles-jwt-claim: "userRoles"
      principal-jwt-claim: "sub"
      application-id-jwt-claim: "sub"
      tenant-id-jwt-claim: "iss"
      allowed-tenants: ${csm.platform.authorization.allowedTenants}


