logging:
  level:
    org.keycloak: WARN

management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: "readinessState,argo"

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "https://localhost/auth/realms/cosmotech"
          jwk-set-uri: "https://localhost/auth/realms/cosmotech/protocol/openid-connect/certs"
          audiences:
            - "account"

csm:
  platform:
    authorization:
      mail-jwt-claim: "email"
      roles-jwt-claim: "customRoles"
      principal-jwt-claim: "sub"
      tenant-id-jwt-claim: "iss"
      allowed-tenants: ["cosmotech"]


