logging:
  level:
    org.keycloak: WARN

management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: "readinessState"

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "https://localhost/auth/realms/cosmotech"
          jwk-set-uri: "https://localhost/auth/realms/cosmotech/protocol/openid-connect/certs"
          audiences:
            - "account"

csm:
  platform:
    authorization:
      mailJwtClaim: "email"
      rolesJwtClaim: "userRoles"
      principalJwtClaim: "sub"
      tenantIdJwtClaim: "iss"
      allowed-tenants:
        - "cosmotech"


