# Spring boot okta starter will read these lines and will inject okta's autoconfigured beans

okta:
  oauth2:
    issuer: ${csm.platform.okta.issuer}
    clientId: ${csm.platform.okta.clientId}
    clientSecret: ${csm.platform.okta.clientSecret}
    audience: ${csm.platform.okta.audience}

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: "https://myOktaDomain/oauth2/default"
          jwk-set-uri: "https://myOktaDomain/oauth2/default/v1/keys"
          audiences:
            - "api://default"

csm:
  platform:
    authorization:
      principal-jwt-claim: "email"
      application-id-jwt-claim: "cid"
      mail-jwt-claim: "sub"
      roles-jwt-claim: "groups"
      allowed-tenants: ["cosmotech"]
