@startuml

title Cosmo Tech Plaform API Schemas Diagram

entity Connector { 
    id: String
    * key: String
    * name: String
    description: String
    * repository: String
    * version: String
    tags: List<String>
    ownerId: String
    url: String
    * ioTypes: List<String>
    parameterGroups: List<ConnectorParameterGroup>
}

entity ConnectorParameter { 
    * id: String
    * label: String
    * valueType: String
    options: List<String>
    default: String
    envVar: String
}

entity ConnectorParameterGroup { 
    * id: String
    * label: String
    * parameters: List<ConnectorParameter>
}

entity Dataset { 
    id: String
    * name: String
    description: String
    ownerId: String
    tags: List<String>
    * connector: DatasetConnector
    fragmentsIds: List<String>
    validatorId: String
    compatibility: List<DatasetCompatibility>
}

entity DatasetCompatibility { 
    * solutionKey: String
    minimumVersion: String
    maximumVersion: String
}

entity DatasetConnector { 
    * id: String
    parametersValues: Map
}

entity DatasetCopyParameters { 
    sourceId: String
    targetId: String
    options: Map
}

entity Organization { 
    id: String
    * name: String
    ownerId: String
    users: List<OrganizationUser>
    services: OrganizationServices
}

entity OrganizationService { 
    cloudService: String
    baseUri: String
    platformService: String
    resourceUri: String
    credentials: Map
}

entity OrganizationServices { 
    tenantCredentials: Map
    storage: OrganizationService
    solutionsContainerRegistry: OrganizationService
}

entity OrganizationUser { 
    id: String
    * name: String
    organizationId: String
    * roles: List<String>
}

entity Platform { 
    * name: String
    description: String
    * version: String
    * ownerId: String
    apiHost: String
    webAppUrl: String
    * services: PlatformServices
}

entity PlatformService { 
    cloudService: String
    baseUri: String
    resourceUri: String
    credentials: Map
    options: Map
}

entity PlatformServices { 
    * provider: String
    credentials: Map
    storage: PlatformService
    coreContainerRegistry: PlatformService
    solutionsContainerRegistry: PlatformService
    eventBusCluster: PlatformService
    dataWarehouseCluster: PlatformService
    databaseCluster: PlatformService
    keyVault: PlatformService
    kubernetesCluster: PlatformService
    directory: PlatformService
    monitoring: PlatformService
    analytic: PlatformService
}

entity RunTemplate { 
    * id: String
    * name: String
    description: String
    csmSimulation: String
    tags: List<String>
    computeSize: String
    parametersHandlerResource: RunTemplateResourceStorage
    datasetValidatorResource: RunTemplateResourceStorage
    preRunResource: RunTemplateResourceStorage
    engineResource: RunTemplateResourceStorage
    postRunResource: RunTemplateResourceStorage
    sendDatasetsToDataWarehouse: Boolean
    sendInputParametersToDataWarehouse: Boolean
    parameterGroups: List<String>
}

entity RunTemplateParameter { 
    * id: String
    * labels: Map
    * varType: String
    options: Map
}

entity RunTemplateParameterGroup { 
    * id: String
    * labels: Map
    isTable: Boolean
    options: Map
    parentId: String
    * parameters: List<String>
}

entity RunTemplateParameterValue { 
    * parameterId: String
    varType: String
    * value: String
}

entity RunTemplateResourceStorage { 
    * storageType: String
    * resourcePath: String
    storageOptions: Map
}

entity Scenario { 
    id: String
    * name: String
    description: String
    tags: List<String>
    parentId: String
    ownerId: String
    solutionId: String
    runTemplateId: String
    users: List<ScenarioUser>
    state: String
    creationDate: String
    ownerName: String
    solutionName: String
    runTemplateName: String
    datasetList: List<String>
    parametersValues: List<ScenarioRunTemplateParameterValue>
}

entity ScenarioChangedParameterValue { 
    parameterId: String
    varType: String
    value: String
    comparedValue: String
}

entity ScenarioComparisonResult { 
    scenarioId: String
    comparedScenarioId: String
    changedValues: List<ScenarioChangedParameterValue>
}

entity ScenarioRun { 
    id: String
    jobId: String
    ownerId: String
    workspaceId: String
    workspaceName: String
    scenarioId: String
    scenarioName: String
    solutionId: String
    solutionName: String
    solutionVersion: String
    runTemplateId: String
    runTemplateName: String
    computeSize: String
    state: String
    failedStep: String
    failedContainerId: String
    startTime: String
    endTime: String
    datasetList: List<String>
    parametersValues: List<RunTemplateParameterValue>
    sendInputToDataWarehouse: Boolean
    dataWarehouseDB: String
    resultsEventBusResourceUri: String
    scenariorunEventBusResourceUri: String
    nodeLabel: String
    fetchDatasetContainers: List<ScenarioRunContainer>
    fetchScenarioParametersContainer: ScenarioRunContainer
    applyParametersContainer: ScenarioRunContainer
    validateDataContainer: ScenarioRunContainer
    sendDataWarehouseContainer: ScenarioRunContainer
    preRunContainer: ScenarioRunContainer
    runContainer: ScenarioRunContainer
    postRunContainer: ScenarioRunContainer
}

entity ScenarioRunContainer { 
    id: String
    envVars: Map
    image: String
    runArgs: List<String>
}

entity ScenarioRunContainerLog { 
    timeGenerated: String
    entrySource: String
    logEntry: String
}

entity ScenarioRunContainerLogs { 
    container: ScenarioRunContainer
    computer: String
    logs: List<ScenarioRunContainerLog>
    textLog: String
}

entity ScenarioRunLogs { 
    scenariorunId: String
    options: ScenarioRunLogsOptions
    fetchDatasetLogs: List<ScenarioRunContainerLogs>
    fetchScenarioParametersLog: ScenarioRunContainerLogs
    applyParametersLogs: ScenarioRunContainerLogs
    validateDataLogs: ScenarioRunContainerLogs
    sendDataWarehouseLogs: ScenarioRunContainerLogs
    preRunLogs: ScenarioRunContainerLogs
    runLogs: ScenarioRunContainerLogs
    postRunLogs: ScenarioRunContainerLogs
}

entity ScenarioRunLogsOptions { 
    containerIds: List<String>
    plainText: Boolean
}

entity ScenarioRunSearch { 
    solutionId: String
    runTemplateId: String
    workspaceId: String
    scenarioId: String
    state: String
    jobId: String
    ownerId: String
}

entity ScenarioRunStart { 
    workspaceId: String
    scenarioId: String
}

entity ScenarioRunStartContainers { 
    nodeLabel: String
    fetchDatasetContainers: List<ScenarioRunContainer>
    fetchScenarioParametersContainer: ScenarioRunContainer
    applyParametersContainer: ScenarioRunContainer
    validateDataContainer: ScenarioRunContainer
    sendDataWarehouseContainer: ScenarioRunContainer
    preRunContainer: ScenarioRunContainer
    runContainer: ScenarioRunContainer
    postRunContainer: ScenarioRunContainer
}

entity ScenarioRunStartSolution { 
    solutionId: String
    runTemplateId: String
    datasetList: List<String>
    parametersValues: List<RunTemplateParameterValue>
    sendInputToDataWarehouse: Boolean
    dataWarehouseDB: String
    resultsEventBusResourceUri: String
    scenariorunEventBusResourceUri: String
}

entity ScenarioRunTemplateParameterValue { 
    * parameterId: String
    varType: String
    * value: String
    isInherited: String
}

entity ScenarioUser { 
    * id: String
    name: String
    * roles: String
}

entity Solution { 
    id: String
    * key: String
    * name: String
    description: String
    * repository: String
    csmSimulator: String
    * version: String
    ownerId: String
    url: String
    tags: List<String>
    parameters: List<RunTemplateParameter>
    parameterGroups: List<RunTemplateParameterGroup>
    run_templates: List<RunTemplate>
}

entity User { 
    id: String
    * name: String
    * platformRoles: List<String>
    organizations: List<UserOrganization>
}

entity UserOrganization { 
    id: String
    name: String
    roles: List<String>
    workspaces: List<UserWorkspace>
}

entity UserWorkspace { 
    id: String
    name: String
    roles: List<String>
}

entity Validator { 
    * id: String
    * name: String
    description: String
    * repository: String
    * version: String
    ownerId: String
    url: String
    tags: List<String>
}

entity ValidatorRun { 
    id: String
    validatorId: String
    validatorName: String
    * datasetId: String
    datasetName: String
    state: String
    containerId: String
    logs: String
}

entity Workspace { 
    id: String
    * name: String
    description: String
    version: String
    tags: List<String>
    ownerId: String
    * solution: WorkspaceSolution
    users: List<WorkspaceUser>
    webApp: WorkspaceWebApp
    services: WorkspaceServices
    sendInputToDataWarehouse: Boolean
}

entity WorkspaceFile { 
    fileName: String
}

entity WorkspaceService { 
    cloudService: String
    baseUri: String
    platformService: String
    resourceUri: String
    credentials: Map
}

entity WorkspaceServices { 
    tenantCredentials: Map
    resultsEventBus: WorkspaceService
    scenariorunEventBus: WorkspaceService
    dataWarehouse: WorkspaceService
    storage: WorkspaceService
}

entity WorkspaceSolution { 
    * solutionId: String
    runTemplateFilter: List<String>
    defaultRunTemplateDataset: Map
}

entity WorkspaceUser { 
    * id: String
    name: String
    * roles: List<String>
}

entity WorkspaceWebApp { 
    * url: String
    iframes: Map
    options: Map
}


Connector -- "0..*" ConnectorParameterGroup : parameterGroups
Organization -- "0..*" OrganizationUser : users
Organization -- OrganizationServices : services
User -- "0..*" UserOrganization : organizations
Platform -- PlatformServices : services
ScenarioRunStartSolution -- "0..*" RunTemplateParameterValue : parametersValues
RunTemplate -- RunTemplateResourceStorage : parametersHandlerResource
RunTemplate -- RunTemplateResourceStorage : datasetValidatorResource
RunTemplate -- RunTemplateResourceStorage : preRunResource
RunTemplate -- RunTemplateResourceStorage : engineResource
RunTemplate -- RunTemplateResourceStorage : postRunResource
ScenarioRunContainerLogs -- ScenarioRunContainer : container
ScenarioRunContainerLogs -- "0..*" ScenarioRunContainerLog : logs
UserOrganization -- "0..*" UserWorkspace : workspaces
ScenarioRunLogs -- ScenarioRunLogsOptions : options
ScenarioRunLogs -- "0..*" ScenarioRunContainerLogs : fetchDatasetLogs
ScenarioRunLogs -- ScenarioRunContainerLogs : fetchScenarioParametersLog
ScenarioRunLogs -- ScenarioRunContainerLogs : applyParametersLogs
ScenarioRunLogs -- ScenarioRunContainerLogs : validateDataLogs
ScenarioRunLogs -- ScenarioRunContainerLogs : sendDataWarehouseLogs
ScenarioRunLogs -- ScenarioRunContainerLogs : preRunLogs
ScenarioRunLogs -- ScenarioRunContainerLogs : runLogs
ScenarioRunLogs -- ScenarioRunContainerLogs : postRunLogs
Solution -- "0..*" RunTemplateParameter : parameters
Solution -- "0..*" RunTemplateParameterGroup : parameterGroups
Solution -- "0..*" RunTemplate : run_templates
ScenarioComparisonResult -- "0..*" ScenarioChangedParameterValue : changedValues
Dataset -- DatasetConnector : connector
Dataset -- "0..*" DatasetCompatibility : compatibility
WorkspaceServices -- WorkspaceService : resultsEventBus
WorkspaceServices -- WorkspaceService : scenariorunEventBus
WorkspaceServices -- WorkspaceService : dataWarehouse
WorkspaceServices -- WorkspaceService : storage
ConnectorParameterGroup -- "0..*" ConnectorParameter : parameters
OrganizationServices -- OrganizationService : storage
OrganizationServices -- OrganizationService : solutionsContainerRegistry
Scenario -- "0..*" ScenarioUser : users
Scenario -- "0..*" ScenarioRunTemplateParameterValue : parametersValues
ScenarioRun -- "0..*" RunTemplateParameterValue : parametersValues
ScenarioRun -- "0..*" ScenarioRunContainer : fetchDatasetContainers
ScenarioRun -- ScenarioRunContainer : fetchScenarioParametersContainer
ScenarioRun -- ScenarioRunContainer : applyParametersContainer
ScenarioRun -- ScenarioRunContainer : validateDataContainer
ScenarioRun -- ScenarioRunContainer : sendDataWarehouseContainer
ScenarioRun -- ScenarioRunContainer : preRunContainer
ScenarioRun -- ScenarioRunContainer : runContainer
ScenarioRun -- ScenarioRunContainer : postRunContainer
PlatformServices -- PlatformService : storage
PlatformServices -- PlatformService : coreContainerRegistry
PlatformServices -- PlatformService : solutionsContainerRegistry
PlatformServices -- PlatformService : eventBusCluster
PlatformServices -- PlatformService : dataWarehouseCluster
PlatformServices -- PlatformService : databaseCluster
PlatformServices -- PlatformService : keyVault
PlatformServices -- PlatformService : kubernetesCluster
PlatformServices -- PlatformService : directory
PlatformServices -- PlatformService : monitoring
PlatformServices -- PlatformService : analytic
ScenarioRunStartContainers -- "0..*" ScenarioRunContainer : fetchDatasetContainers
ScenarioRunStartContainers -- ScenarioRunContainer : fetchScenarioParametersContainer
ScenarioRunStartContainers -- ScenarioRunContainer : applyParametersContainer
ScenarioRunStartContainers -- ScenarioRunContainer : validateDataContainer
ScenarioRunStartContainers -- ScenarioRunContainer : sendDataWarehouseContainer
ScenarioRunStartContainers -- ScenarioRunContainer : preRunContainer
ScenarioRunStartContainers -- ScenarioRunContainer : runContainer
ScenarioRunStartContainers -- ScenarioRunContainer : postRunContainer
Workspace -- WorkspaceSolution : solution
Workspace -- "0..*" WorkspaceUser : users
Workspace -- WorkspaceWebApp : webApp
Workspace -- WorkspaceServices : services

@enduml