@startuml

title Cosmo Tech Platform API Schemas Diagram

entity ComponentRolePermissions {
    component: String
    roles: Map
}

entity Connector {
    id: String
    key: String
    name: String
    description: String
    repository: String
    version: String
    tags: List<String>
    ownerId: String
    url: String
    ioTypes: List<IoTypesEnum>
    parameterGroups: List<ConnectorParameterGroup>
}

entity ConnectorParameter {
    * id: String
    * label: String
    valueType: String
    options: List<String>
    default: String
    envVar: String
}

entity ConnectorParameterGroup {
    * id: String
    * label: String
    * parameters: List<ConnectorParameter>
}

entity ContainerResourceSizeInfo {
    * cpu: String
    * memory: String
}

entity ContainerResourceSizing {
    * requests: ContainerResourceSizeInfo
    * limits: ContainerResourceSizeInfo
}

entity CreatedRun {
    * id: String
}

entity Dataset {
    id: String
    name: String
    description: String
    ownerId: String
    ownerName: String
    organizationId: String
    parentId: String
    linkedWorkspaceIdList: List<String>
    twingraphId: String
    main: Boolean
    creationDate: Long
    refreshDate: Long
    sourceType: DatasetSourceType
    source: SourceInfo
    ingestionStatus: IngestionStatusEnum
    twincacheStatus: TwincacheStatusEnum
    queries: List<String>
    tags: List<String>
    connector: DatasetConnector
    fragmentsIds: List<String>
    validatorId: String
    compatibility: List<DatasetCompatibility>
    security: DatasetSecurity
}

entity DatasetAccessControl {
    * id: String
    * role: String
}

entity DatasetCompatibility {
    * solutionKey: String
    minimumVersion: String
    maximumVersion: String
}

entity DatasetConnector {
    id: String
    name: String
    version: String
    parametersValues: Map
}

entity DatasetCopyParameters {
    sourceId: String
    targetId: String
    options: Map
}

entity DatasetRole {
    * role: String
}

entity DatasetSearch {
    * datasetTags: List<String>
}

entity DatasetSecurity {
    * default: String
    * accessControlList: List<DatasetAccessControl>
}

entity DatasetSourceType {
}

entity DatasetTwinGraphHash {
    hash: String
}

entity DatasetTwinGraphInfo {
    jobId: String
    datasetId: String
    status: String
}

entity DatasetTwinGraphQuery {
    * query: String
}

entity DeleteHistoricalData {
    * enable: Boolean
    pollFrequency: Integer
    timeOut: Integer
}

entity FileUploadMetadata {
    name: String
    size: Integer
}

entity FileUploadValidation {
    nodes: List<FileUploadMetadata>
    edges: List<FileUploadMetadata>
}

entity GraphProperties {
    type: String
    source: String
    target: String
    name: String
    params: String
}

entity IngestionStatusEnum {
}

entity IoTypesEnum {
}

entity Organization {
    id: String
    name: String
    ownerId: String
    security: OrganizationSecurity
}

entity OrganizationAccessControl {
    * id: String
    * role: String
}

entity OrganizationCreateRequest {
    * name: String
    security: OrganizationSecurity
}

entity OrganizationRole {
    * role: String
}

entity OrganizationSecurity {
    * default: String
    * accessControlList: List<OrganizationAccessControl>
}

entity OrganizationUpdateRequest {
    name: String
}

entity QueryResult {
    result: List<Map>
}

entity ResourceSizeInfo {
    * cpu: String
    * memory: String
}

entity Run {
    id: String
    state: RunState
    organizationId: String
    workflowId: String
    csmSimulationRun: String
    generateName: String
    workflowName: String
    ownerId: String
    workspaceId: String
    workspaceKey: String
    runnerId: String
    solutionId: String
    runTemplateId: String
    computeSize: String
    createdAt: String
    datasetList: List<String>
    parametersValues: List<RunTemplateParameterValue>
    nodeLabel: String
    containers: List<RunContainer>
}

entity RunContainer {
    id: String
    * name: String
    labels: Map
    envVars: Map
    * image: String
    entrypoint: String
    runArgs: List<String>
    dependencies: List<String>
    solutionContainer: Boolean
    nodeLabel: String
    runSizing: ContainerResourceSizing
}

entity RunData {
    database_name: String
    table_name: String
    data: List<Map>
}

entity RunDataQuery {
    * query: String
}

entity RunLogs {
    * runId: String
    * logs: List<RunLogsEntry>
}

entity RunLogsEntry {
    * line: String
}

entity RunResourceRequested {
    cpu: Long
    memory: Long
}

entity RunState {
}

entity RunStatus {
    id: String
    organizationId: String
    workspaceId: String
    runnerId: String
    workflowId: String
    workflowName: String
    startTime: String
    endTime: String
    phase: String
    progress: String
    message: String
    estimatedDuration: Integer
    nodes: List<RunStatusNode>
    state: RunState
}

entity RunStatusNode {
    id: String
    name: String
    containerName: String
    outboundNodes: List<String>
    resourcesDuration: RunResourceRequested
    estimatedDuration: Integer
    hostNodeName: String
    message: String
    phase: String
    progress: String
    startTime: String
    endTime: String
}

entity RunTemplate {
    * id: String
    name: String
    labels: Map
    description: String
    csmSimulation: String
    tags: List<String>
    computeSize: String
    runSizing: RunTemplateResourceSizing
    noDataIngestionState: Boolean
    fetchDatasets: Boolean
    scenarioDataDownloadTransform: Boolean
    fetchScenarioParameters: Boolean
    applyParameters: Boolean
    validateData: Boolean
    sendDatasetsToDataWarehouse: Boolean
    sendInputParametersToDataWarehouse: Boolean
    preRun: Boolean
    run: Boolean
    postRun: Boolean
    parametersJson: Boolean
    parametersHandlerSource: RunTemplateStepSource
    datasetValidatorSource: RunTemplateStepSource
    preRunSource: RunTemplateStepSource
    runSource: RunTemplateStepSource
    postRunSource: RunTemplateStepSource
    scenariodataTransformSource: RunTemplateStepSource
    parameterGroups: List<String>
    stackSteps: Boolean
    gitRepositoryUrl: String
    gitBranchName: String
    runTemplateSourceDir: String
    orchestratorType: RunTemplateOrchestrator
    executionTimeout: Integer
    deleteHistoricalData: DeleteHistoricalData
}

entity RunTemplateOrchestrator {
}

entity RunTemplateParameter {
    * id: String
    labels: Map
    varType: String
    defaultValue: String
    minValue: String
    maxValue: String
    regexValidation: String
    options: Map
}

entity RunTemplateParameterGroup {
    * id: String
    labels: Map
    isTable: Boolean
    options: Map
    parentId: String
    parameters: List<String>
}

entity RunTemplateParameterValue {
    * parameterId: String
    varType: String
    * value: String
}

entity RunTemplateResourceSizing {
    * requests: ResourceSizeInfo
    * limits: ResourceSizeInfo
}

entity RunTemplateStepSource {
}

entity Runner {
    id: String
    name: String
    description: String
    tags: List<String>
    parentId: String
    ownerId: String
    rootId: String
    solutionId: String
    runTemplateId: String
    organizationId: String
    workspaceId: String
    creationDate: Long
    lastUpdate: Long
    ownerName: String
    solutionName: String
    runTemplateName: String
    datasetList: List<String>
    runSizing: RunnerResourceSizing
    parametersValues: List<RunnerRunTemplateParameterValue>
    lastRunId: String
    validationStatus: RunnerValidationStatus
    security: RunnerSecurity
}

entity RunnerAccessControl {
    * id: String
    * role: String
}

entity RunnerResourceSizing {
    * requests: ResourceSizeInfo
    * limits: ResourceSizeInfo
}

entity RunnerRole {
    * role: String
}

entity RunnerRunTemplateParameterValue {
    * parameterId: String
    varType: String
    * value: String
    isInherited: Boolean
}

entity RunnerSecurity {
    * default: String
    * accessControlList: List<RunnerAccessControl>
}

entity RunnerValidationStatus {
}

entity SendRunDataRequest {
    id: String
    data: List<Map>
}

entity Solution {
    id: String
    organizationId: String
    key: String
    name: String
    description: String
    repository: String
    alwaysPull: Boolean
    csmSimulator: String
    version: String
    ownerId: String
    sdkVersion: String
    url: String
    tags: List<String>
    parameters: List<RunTemplateParameter>
    parameterGroups: List<RunTemplateParameterGroup>
    * runTemplates: List<RunTemplate>
    security: SolutionSecurity
}

entity SolutionAccessControl {
    * id: String
    * role: String
}

entity SolutionRole {
    * role: String
}

entity SolutionSecurity {
    * default: String
    * accessControlList: List<SolutionAccessControl>
}

entity SourceInfo {
    name: String
    * location: String
    path: String
    jobId: String
}

entity SubDatasetGraphQuery {
    name: String
    description: String
    queries: List<String>
    main: Boolean
}

entity TwinGraphBatchResult {
    * totalLines: Integer
    * processedLines: Integer
    * errors: List<String>
}

entity TwincacheStatusEnum {
}

entity Workspace {
    id: String
    organizationId: String
    * key: String
    * name: String
    description: String
    linkedDatasetIdList: List<String>
    version: String
    tags: List<String>
    ownerId: String
    * solution: WorkspaceSolution
    webApp: WorkspaceWebApp
    sendInputToDataWarehouse: Boolean
    useDedicatedEventHubNamespace: Boolean
    dedicatedEventHubSasKeyName: String
    dedicatedEventHubAuthenticationStrategy: String
    sendScenarioRunToEventHub: Boolean
    sendScenarioMetadataToEventHub: Boolean
    datasetCopy: Boolean
    security: WorkspaceSecurity
}

entity WorkspaceAccessControl {
    * id: String
    * role: String
}

entity WorkspaceFile {
    fileName: String
}

entity WorkspaceRole {
    * role: String
}

entity WorkspaceSecurity {
    * default: String
    * accessControlList: List<WorkspaceAccessControl>
}

entity WorkspaceSolution {
    solutionId: String
    runTemplateFilter: List<String>
    defaultRunTemplateDataset: Map
}

entity WorkspaceWebApp {
    * url: String
    iframes: Map
    options: Map
}


RunTemplateResourceSizing -- ResourceSizeInfo : requests
RunTemplateResourceSizing -- ResourceSizeInfo : limits
DatasetSecurity -- "0..*" DatasetAccessControl : accessControlList
ContainerResourceSizing -- ContainerResourceSizeInfo : requests
ContainerResourceSizing -- ContainerResourceSizeInfo : limits
SolutionSecurity -- "0..*" SolutionAccessControl : accessControlList
RunLogs -- "0..*" RunLogsEntry : logs
WorkspaceSecurity -- "0..*" WorkspaceAccessControl : accessControlList
ConnectorParameterGroup -- "0..*" ConnectorParameter : parameters
RunContainer -- ContainerResourceSizing : runSizing
OrganizationCreateRequest -- OrganizationSecurity : security
Connector -- "0..*" ConnectorParameterGroup : parameterGroups
Runner -- RunnerResourceSizing : runSizing
Runner -- "0..*" RunnerRunTemplateParameterValue : parametersValues
Runner -- RunnerSecurity : security
Organization -- OrganizationSecurity : security
RunStatus -- "0..*" RunStatusNode : nodes
FileUploadValidation -- "0..*" FileUploadMetadata : nodes
FileUploadValidation -- "0..*" FileUploadMetadata : edges
RunTemplate -- RunTemplateResourceSizing : runSizing
RunTemplate -- DeleteHistoricalData : deleteHistoricalData
RunnerSecurity -- "0..*" RunnerAccessControl : accessControlList
RunStatusNode -- RunResourceRequested : resourcesDuration
Solution -- "0..*" RunTemplateParameter : parameters
Solution -- "0..*" RunTemplateParameterGroup : parameterGroups
Solution -- "0..*" RunTemplate : runTemplates
Solution -- SolutionSecurity : security
Dataset -- SourceInfo : source
Dataset -- DatasetConnector : connector
Dataset -- "0..*" DatasetCompatibility : compatibility
Dataset -- DatasetSecurity : security
Run -- "0..*" RunTemplateParameterValue : parametersValues
Run -- "0..*" RunContainer : containers
OrganizationSecurity -- "0..*" OrganizationAccessControl : accessControlList
RunnerResourceSizing -- ResourceSizeInfo : requests
RunnerResourceSizing -- ResourceSizeInfo : limits
Workspace -- WorkspaceSolution : solution
Workspace -- WorkspaceWebApp : webApp
Workspace -- WorkspaceSecurity : security

@enduml