@startuml

title Cosmo Tech Plaform API Schemas Diagram

entity Connector { 
    id: String
    * key: String
    * name: String
    description: String
    * repository: String
    * version: String
    tags: List<String>
    ownerId: String
    url: String
    azureManagedIdentity: Boolean
    azureAuthenticationWithCustomerAppRegistration: Boolean
    * ioTypes: List<String>
    parameterGroups: List<ConnectorParameterGroup>
}

entity ConnectorParameter { 
    * id: String
    * label: String
    valueType: String
    options: List<String>
    default: String
    envVar: String
}

entity ConnectorParameterGroup { 
    * id: String
    * label: String
    * parameters: List<ConnectorParameter>
}

entity Dataset { 
    id: String
    name: String
    description: String
    ownerId: String
    tags: List<String>
    connector: DatasetConnector
    fragmentsIds: List<String>
    validatorId: String
    compatibility: List<DatasetCompatibility>
}

entity DatasetCompatibility { 
    * solutionKey: String
    minimumVersion: String
    maximumVersion: String
}

entity DatasetConnector { 
    id: String
    name: String
    version: String
    parametersValues: Map
}

entity DatasetCopyParameters { 
    sourceId: String
    targetId: String
    options: Map
}

entity Organization { 
    id: String
    name: String
    ownerId: String
    users: List<OrganizationUser>
    services: OrganizationServices
}

entity OrganizationService { 
    cloudService: String
    baseUri: String
    platformService: String
    resourceUri: String
    credentials: Map
}

entity OrganizationServices { 
    tenantCredentials: Map
    storage: OrganizationService
    solutionsContainerRegistry: OrganizationService
}

entity OrganizationUser { 
    id: String
    name: String
    * roles: List<String>
}

entity RunTemplate { 
    * id: String
    * name: String
    description: String
    csmSimulation: String
    tags: List<String>
    computeSize: String
    fetchDatasets: Boolean
    fetchScenarioParameters: Boolean
    applyParameters: Boolean
    validateData: Boolean
    sendDatasetsToDataWarehouse: Boolean
    sendInputParametersToDataWarehouse: Boolean
    preRun: Boolean
    run: Boolean
    postRun: Boolean
    parametersJson: Boolean
    parametersHandlerSource: RunTemplateStepSource
    datasetValidatorSource: RunTemplateStepSource
    preRunSource: RunTemplateStepSource
    runSource: RunTemplateStepSource
    postRunSource: RunTemplateStepSource
    parameterGroups: List<String>
}

entity RunTemplateHandlerId { 
}

entity RunTemplateParameter { 
    * id: String
    * labels: Map
    * varType: String
    defaultValue: String
    minValue: String
    maxValue: String
    regexValidation: String
    options: Map
}

entity RunTemplateParameterGroup { 
    * id: String
    * labels: Map
    isTable: Boolean
    options: Map
    parentId: String
    * parameters: List<String>
}

entity RunTemplateParameterValue { 
    * parameterId: String
    varType: String
    * value: String
}

entity RunTemplateStepSource { 
}

entity Scenario { 
    id: String
    name: String
    description: String
    tags: List<String>
    parentId: String
    ownerId: String
    rootId: String
    solutionId: String
    runTemplateId: String
    workspaceId: String
    users: List<ScenarioUser>
    state: String
    creationDate: Date
    lastUpdate: Date
    ownerName: String
    solutionName: String
    runTemplateName: String
    datasetList: List<String>
    parametersValues: List<ScenarioRunTemplateParameterValue>
    lastRun: ScenarioLastRun
}

entity ScenarioChangedParameterValue { 
    parameterId: String
    varType: String
    value: String
    comparedValue: String
}

entity ScenarioComparisonResult { 
    scenarioId: String
    comparedScenarioId: String
    changedValues: List<ScenarioChangedParameterValue>
}

entity ScenarioLastRun { 
    scenarioRunId: String
    csmSimulationRun: String
    workflowId: String
    workflowName: String
}

entity ScenarioRun { 
    id: String
    organizationId: String
    workflowId: String
    csmSimulationRun: String
    generateName: String
    workflowName: String
    ownerId: String
    workspaceId: String
    workspaceKey: String
    scenarioId: String
    solutionId: String
    runTemplateId: String
    computeSize: String
    datasetList: List<String>
    parametersValues: List<RunTemplateParameterValue>
    sendDatasetsToDataWarehouse: Boolean
    sendInputParametersToDataWarehouse: Boolean
    nodeLabel: String
    containers: List<ScenarioRunContainer>
}

entity ScenarioRunContainer { 
    id: String
    * name: String
    labels: Map
    envVars: Map
    * image: String
    entrypoint: String
    runArgs: List<String>
    dependencies: List<String>
}

entity ScenarioRunContainerLogs { 
    nodeId: String
    containerName: String
    children: List<String>
    logs: String
}

entity ScenarioRunLogs { 
    scenariorunId: String
    containers: Map
}

entity ScenarioRunSearch { 
    solutionId: String
    runTemplateId: String
    workspaceId: String
    scenarioId: String
    state: String
    workflowId: String
    workflowName: String
    ownerId: String
}

entity ScenarioRunStartContainers { 
    generateName: String
    * csmSimulationId: String
    nodeLabel: String
    * containers: List<ScenarioRunContainer>
}

entity ScenarioRunStatus { 
    id: String
    organizationId: String
    workflowId: String
    workflowName: String
    startTime: String
    endTime: String
    phase: String
    progress: String
    message: String
    estimatedDuration: Integer
    nodes: List<ScenarioRunStatusNode>
}

entity ScenarioRunStatusNode { 
    id: String
    name: String
    containerName: String
    estimatedDuration: Integer
    hostNodeName: String
    message: String
    phase: String
    progress: String
    startTime: String
    endTime: String
}

entity ScenarioRunTemplateParameterValue { 
    * parameterId: String
    varType: String
    * value: String
    isInherited: Boolean
}

entity ScenarioUser { 
    * id: String
    name: String
    * roles: List<String>
}

entity Solution { 
    id: String
    * key: String
    * name: String
    description: String
    * repository: String
    csmSimulator: String
    * version: String
    ownerId: String
    url: String
    tags: List<String>
    parameters: List<RunTemplateParameter>
    parameterGroups: List<RunTemplateParameterGroup>
    * runTemplates: List<RunTemplate>
}

entity User { 
    id: String
    name: String
    platformRoles: List<String>
    organizations: List<UserOrganization>
}

entity UserOrganization { 
    id: String
    name: String
    roles: List<String>
    workspaces: List<UserWorkspace>
}

entity UserWorkspace { 
    id: String
    name: String
    roles: List<String>
}

entity Validator { 
    * id: String
    * name: String
    description: String
    * repository: String
    * version: String
    ownerId: String
    url: String
    tags: List<String>
}

entity ValidatorRun { 
    id: String
    validatorId: String
    validatorName: String
    * datasetId: String
    datasetName: String
    state: String
    containerId: String
    logs: String
}

entity Workspace { 
    id: String
    * key: String
    * name: String
    description: String
    version: String
    tags: List<String>
    ownerId: String
    * solution: WorkspaceSolution
    users: List<WorkspaceUser>
    webApp: WorkspaceWebApp
    sendInputToDataWarehouse: Boolean
}

entity WorkspaceFile { 
    fileName: String
}

entity WorkspaceSolution { 
    solutionId: String
    runTemplateFilter: List<String>
    defaultRunTemplateDataset: Map
}

entity WorkspaceUser { 
    * id: String
    name: String
    * roles: List<String>
}

entity WorkspaceWebApp { 
    * url: String
    iframes: Map
    options: Map
}


Connector -- "0..*" ConnectorParameterGroup : parameterGroups
Organization -- "0..*" OrganizationUser : users
Organization -- OrganizationServices : services
User -- "0..*" UserOrganization : organizations
UserOrganization -- "0..*" UserWorkspace : workspaces
Solution -- "0..*" RunTemplateParameter : parameters
Solution -- "0..*" RunTemplateParameterGroup : parameterGroups
Solution -- "0..*" RunTemplate : runTemplates
ScenarioComparisonResult -- "0..*" ScenarioChangedParameterValue : changedValues
Dataset -- DatasetConnector : connector
Dataset -- "0..*" DatasetCompatibility : compatibility
ConnectorParameterGroup -- "0..*" ConnectorParameter : parameters
OrganizationServices -- OrganizationService : storage
OrganizationServices -- OrganizationService : solutionsContainerRegistry
Scenario -- "0..*" ScenarioUser : users
Scenario -- "0..*" ScenarioRunTemplateParameterValue : parametersValues
Scenario -- ScenarioLastRun : lastRun
ScenarioRun -- "0..*" RunTemplateParameterValue : parametersValues
ScenarioRun -- "0..*" ScenarioRunContainer : containers
ScenarioRunStatus -- "0..*" ScenarioRunStatusNode : nodes
ScenarioRunStartContainers -- "0..*" ScenarioRunContainer : containers
Workspace -- WorkspaceSolution : solution
Workspace -- "0..*" WorkspaceUser : users
Workspace -- WorkspaceWebApp : webApp

@enduml