openapi: 3.0.3

info:
  title: ""
  version: ""

security:
  - oAuth2AuthCode: []

tags:
- name: IAMInfo
  description: IAMInfo Management

paths:
  /iaminfo/members:
    get:
      operationId: listIAMMembers
      tags:
        - IAMInfo
      summary: Get ALL IAM members list
      responses:
        "200":
          description: The ALL members list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members'
            application/yaml:
              schema:
                $ref: '#/components/schemas/Members'
  /iaminfo/groups:
    get:
      operationId: listIAMGroups
      tags:
        - IAMInfo
      summary: Get the list of all groups
      responses:
        "200":
          description: The list of all groups
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/yaml:
              schema:
                type: array
                items:
                  type: string

components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: "https://example.com/authorize"
          tokenUrl: "https://example.com/token"
          scopes: {}
  schemas:
    Members:
      type: object
      description: The members, including users and groups
      properties:
        users:
          type: array
          description: The list of users in the IAM
          items:
            $ref: '#/components/schemas/MemberUser'
          default: []
        groups:
          type: array
          description: The list of groups in the IAM
          items:
            $ref: '#/components/schemas/MemberGroup'
          default: []
      required:
        - users
        - groups

    MemberUser:
      type: object
      description: A user member of the IAM
      properties:
        id:
          type: string
          description: The user id
        role:
          type: string
          description: The user role in the IAM
      required:
        - id
        - role

    MemberGroup:
      type: object
      description: A group member of the IAM
      properties:
        id:
          type: string
          description: The group id
        role:
          type: string
          description: The user role in the IAM
        users:
          type: array
          description: The list of users in the group
          items:
            type: string
      required:
        - id
        - role
        - users
