#
# Sample configuration file for the dev profile.
# Feel free to customize this file or, if needed, reach out to the Cosmo Tech for support.
#
# NOTE: Not all supported properties (declared in api/src/main/resources/application.yml)
# are included here.
# Only the relevant ones that need to be set are listed here.
#
logging:
  level:
    com.cosmotech: DEBUG
    web: INFO
    org.springframework: WARN

server:
  error:
    include-stacktrace: always

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8080

csm:
  platform:
    # Disable kubernetes access for outside a cluster or without a current context
    # If enabled locally, one can override the kube context by passing '-PjvmArgs=-DuseKubernetesContext=my-context'
    # to the bootRun gradle task
    kubernetesAccessEnabled: false
    identityProvider:
      code: azure
      # Use to overwrite openAPI configuration
      authorizationUrl: "[fill-this-value]"
      tokenUrl: "[fill-this-value]"
      defaultScopes:
        "[fill-this-value]": "[fill-this-value]"
      containerScopes:
        "[fill-this-value]": "[fill-this-value]"
      # Here you can set custom user and admin groups
      # - adminGroup will have same rights that Platform.Admin
      # - userGroup will have same rights that Organization.User
      # - viewerGroup will have same rights that Organization.Viewer
      # adminGroup : "myCustomAdminGroup"
      # userGroup : "myCustomUserGroup"
      # userGroup : "myCustomViewerGroup"
    storage:
      host: "localhost"
      reader:
        username: "storage_reader_username"
        password: "storage_reader_password"
      admin:
        username: "storage_admin_username"
        password: "storage_admin_password"
    eventbus:
      host: "localhost"
      username: "eventbus_admin_username"
      password: "eventbus_admin_password"
    blobPersistence:
      path: /tmp/cosmotech-api-data-dev
    argo:
      base-uri: "http://localhost:2746"
    azure:
      credentials:
        # TODO Fill these values or reach out to the Cosmo Tech Platform Team for support
        tenantId: "e413b834-8be8-4822-a370-be619545cb49"
        clientId: "[fill-this-value]"
        clientSecret: "[fill-this-value]"
      dataWarehouseCluster:
        baseUri: "https://phoenixdev.westeurope.kusto.windows.net"
        options:
          ingestionUri: "https://ingest-phoenixdev.westeurope.kusto.windows.net"
      eventBus:
        baseUri: "amqps://phoenixdev.servicebus.windows.net"
      containerRegistries:
        solutions: "localhost:5000"
