spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "user_rabbit"
    password: "pwd_rabbit"
  data:
    redis:
      host: "localhost"
      username: "default"
      port: 6379
      # Leave it as blank as there's no auth with test container
      password:
      client-type: jedis

logging:
  level:
    com.cosmotech: DEBUG
    web: INFO
    org.springframework: INFO
    com.redis: DEBUG

management:
  endpoints:
    enabled-by-default: false

csm:
  platform:
    identityProvider:
      code: on_premise_one
      authorizationUrl: "http://fake_url:8080/authorize"
      tokenUrl: "http://fake_url:8080/token"
      containerScopes:
        '[https://api.cosmotech.com]': "Default scope"
      serverBaseUrl: "http://fake_url:8080"
      identity:
        clientId: "my_client_id"
        clientSecret: "my_client_secret"
        tenantId: "my_tenant_id"
    runOutsideKubernetes: true
    metrics:
      enabled: false
    api:
      # API Base Path for OpenAPI-generated controllers.
      # Might conflict with the SpringBoot context path, hence leaving it at the root
      base-path: /
      base-url: "http://fake_url:8080"
      version: latest
    id-generator:
      type: hashid
    event-publisher:
      type: in_process
    images:
      scenario-fetch-parameters: cosmo-tech/fetch-scenario-parameters
      send-datawarehouse: cosmo-tech/azure-data-explorer-connector
      scenario-data-upload: cosmo-tech/azure-storage-publish:latest
    containers:
      - name: "ADTTwingraphImport"
        imageRegistry: "ghcr.io"
        imageName: "cosmo-tech/adt-twincache-connector"
        imageVersion: "0.0.5"
      - name: "StorageTwingraphImport"
        imageRegistry: "ghcr.io"
        imageName: "cosmo-tech/azstorage-twincache-connector"
        imageVersion: "latest"
    upload:
      authorized-mime-types:
        workspaces:
          - application/zip
          - application/xml
          - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
          - application/x-tika-ooxml
          - text/csv
          - text/plain
          - text/x-yaml
          - application/json
    authorization:
      tenant-id-jwt-claim: "iss"
      # Note that the way @Value works in Spring does not make it possible to inject this sole YAML list.
      # Use CsmPlatformProperties instead !
      allowed-tenants: ["test"]
    argo:
      base-uri: "https://argo-server.argo.svc.cluster.local:2746"
      workflows:
        namespace: phoenix
        node-pool-label: ""
        service-account-name: workflowcsmv2
        storage-class: null
        access-modes:
          # Any in the following list: ReadWriteOnce, ReadOnlyMany, ReadWriteMany, ReadWriteOncePod (K8s 1.22+)
          - ReadWriteOnce
        requests:
          storage: 1Gi
    twincache:
      host: "localhost"
      port: "6379"
      username: "default"
      password: "my-wonderful-password"
      run:
        default-page-size: 5
    internalResultServices:
      enabled: true
      storage:
        host: "localhost"
        port: "5432"
        reader:
          username: "user1"
          password: "pwd1"
        writer:
          username: "user2"
          password: "pwd2"
        admin:
          username: "user3"
          password: "pwd3"
      eventBus:
        host: "localhost"
        default-exchange: "csm-exchange"
        default-queue: "csm"
        default-routing-key: "csm"
        sender:
          username: "user3"
          password: "pwd3"
        listener:
          username: "user4"
          password: "pwd4"
    rbac:
      enabled: true
    containerRegistry:
      provider: "local"
      registryUrl: "http://localhost:5000"
      registryUserName: "default"
      registryPassword: "my-wonderful-password"
    blobPersistence:
      path: /tmp/cosmotech-api-run-test-data
