name: OpenAPI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  merge_openapi_specs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Merge OpenAPI definitions
        run: ./gradlew --info mergeOpenApiFiles

      - name: Archive openapi.yaml
        uses: actions/upload-artifact@v2
        with:
          name: openapi
          path: openapi/openapi.yaml
          retention-days: 3

  validate_openapi:
    # The OpenAPI Generator Gradle Plugin exposes an 'openApiValidate' task,
    # but at this time, it does not work with Gradle 7.0.
    # See https://github.com/OpenAPITools/openapi-generator/issues/9328
    # This job is a different approach for validation, using the Swagger Editor service,
    # as suggested here : https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/
    runs-on: ubuntu-latest
    name: OpenAPI Validator Service
    needs: merge_openapi_specs

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor:v3.16.1
        ports:
          - 80:8080

    steps:
      - uses: actions/checkout@v2

      - name: Validate 'connector' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: connector/src/main/openapi/connectors.yaml

      - name: Validate 'dataset' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: dataset/src/main/openapi/datasets.yaml

      - name: Validate 'organization' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: organization/src/main/openapi/organizations.yaml

      - name: Validate 'scenario' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: scenario/src/main/openapi/scenarios.yaml

      - name: Validate 'scenariorun' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: scenariorun/src/main/openapi/scenarioruns.yaml

      - name: Validate 'solution' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: solution/src/main/openapi/solutions.yaml

      - name: Validate 'user' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: user/src/main/openapi/users.yaml

      - name: Validate 'workspace' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: workspace/src/main/openapi/workspaces.yaml

      - name: Download openapi artifact
        uses: actions/download-artifact@v2
        with:
          name: openapi
      - name: Validate merged OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: openapi.yaml

  upload_merged_openapi:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: validate_openapi
    steps:
      - name: Download openapi artifact
        uses: actions/download-artifact@v2
        with:
          name: openapi

      - name: azure login
        uses: azure/login@v1.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: az storage command
        run: |
          az storage blob upload --account-name csmphoenix --container-name public --name openapi.yaml --file openapi.yaml
