name: OpenAPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ main ]

jobs:
  validate_projects_openapis:
    # The OpenAPI Generator Gradle Plugin exposes an 'openApiValidate' task,
    # but at this time, it does not work with Gradle 7.0.
    # See https://github.com/OpenAPITools/openapi-generator/issues/9328
    # This job is a different approach for validation, using the Swagger Editor service,
    # as suggested here : https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/
    runs-on: ubuntu-latest
    name: OpenAPI Validator Service

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor:v3.18.2
        ports:
          - 80:8080

    strategy:
      fail-fast: false
      matrix:
        project:
          - connector
          - dataset
          - organization
          - scenario
          - scenariorun
          - solution
          - user
          - workspace

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Validate '${{ matrix.project }}' definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: ${{ matrix.project }}/src/main/openapi/${{ matrix.project }}s.yaml

  merge_openapi_specs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Merge OpenAPI definitions
        run: ./gradlew --info mergeOpenApiFiles

      - name: Archive openapi.yaml
        uses: actions/upload-artifact@v2
        with:
          name: openapi
          path: openapi/openapi.yaml
          retention-days: 3

  validate_merged_openapi:
    # The OpenAPI Generator Gradle Plugin exposes an 'openApiValidate' task,
    # but at this time, it does not work with Gradle 7.0.
    # See https://github.com/OpenAPITools/openapi-generator/issues/9328
    # This job is a different approach for validation, using the Swagger Editor service,
    # as suggested here : https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/
    runs-on: ubuntu-latest
    needs: merge_openapi_specs

    services:
      swagger-editor:
        image: swaggerapi/swagger-editor:v3.18.2
        ports:
          - 80:8080

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Download openapi artifact
        uses: actions/download-artifact@v2
        with:
          name: openapi
      - name: Validate merged OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          swagger-editor-url: http://localhost/
          definition-file: openapi.yaml

  generate_doc_and_push_if_needed:
    runs-on: ubuntu-latest
    needs: validate_merged_openapi
    concurrency:
      group: generated-doc_update
      cancel-in-progress: false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Generate Markdown documentation
        run: ./gradlew --info openApiMarkdownGenerate

      - name: Generate UML documentation
        run: ./gradlew --info openApiUmlGenerate

      - name: Set Git identity
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

      - name: Push generated documentation if needed
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git fetch --prune
          git pull --rebase --autostash
          if [[ `git status --porcelain` ]]; then
            git add doc/ openapi/plantuml/
            git commit -m "chore(docs): Update generated documentation" \
              -m "[skip ci]" \
              -m "Co-authored-by: csmplatform <csmplatform@users.noreply.github.com>"
            git pull --rebase
            git push origin main
          fi

  upload_merged_openapi:
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: validate_merged_openapi
    concurrency:
      group: openapi-upload_${{ github.ref }}
      cancel-in-progress: false
    steps:

      - name: Retrieve branch or tag name
        id: refvar
        run: echo "::set-output name=gitRefName::${GITHUB_REF#refs/*/}"

      - name: Download openapi artifact
        uses: actions/download-artifact@v2
        with:
          name: openapi

      - name: azure login
        uses: azure/login@v1.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload tagged openapi.yml to Azure Storage
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          az storage blob upload \
            --account-name csmphoenixdev \
            --container-name public \
            --name openapi-${{ steps.refvar.outputs.gitRefName }}.yaml \
            --file openapi.yaml

      - name: Upload openapi.yml to Azure Storage
        if: github.ref == 'refs/heads/main'
        run: |
          az storage blob upload \
            --account-name csmphoenixdev \
            --container-name public \
            --name openapi.yaml \
            --file openapi.yaml
