name: OpenAPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
      - '!*-test'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - 'main'
      - 'release/**'

jobs:
  validate_projects_openapis:
    runs-on: ubuntu-latest
    name: OpenAPI Validation

    strategy:
      fail-fast: false
      matrix:
        project:
          - api
          - connector-api
          - dataset-api
          - organization-api
          - solution-api
          - workspace-api
          - runner-api
          - run-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate '${{ matrix.project }}' definition
        run: ./gradlew :cosmotech-${{ matrix.project }}:openApiValidate | tee validate.log

      - name: Check issues and recommendations
        run: grep -qvz "Spec has issues or recommendations" validate.log
