name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  push_container_images_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      DOCKER_BUILDKIT: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Retrieve branch or tag name
        id: refvar
        run: echo "::set-output name=gitRefName::${GITHUB_REF#refs/*/}"

      - name: Build local Container Image for scanning
        run: |
          ./gradlew :cosmotech-api:jibDockerBuild \
            -Djib.to.image="com.cosmotech/cosmotech-api:${GITHUB_SHA}"

      - name: Scan Container Image
        id: scan
        # TODO For now, do not block if the container scan action returns issues
        continue-on-error: true
        uses: Azure/container-scan@v0.1
        with:
          image-name: com.cosmotech/cosmotech-api:${{ github.sha }}

      - name: Archive container image scan report
        if: ${{ always() }}
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: container-image-scan-report
          path: ${{ steps.scan.outputs.scan-report-path }}
          retention-days: 3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push API Container Image (tag) to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker image tag com.cosmotech/cosmotech-api:${GITHUB_SHA} \
            ghcr.io/cosmo-tech/cosmotech-api:${{ steps.refvar.outputs.gitRefName }}
          docker image push ghcr.io/cosmo-tech/cosmotech-api:${{ steps.refvar.outputs.gitRefName }}

      - name: Push API Container Image (latest) to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          docker image tag com.cosmotech/cosmotech-api:${GITHUB_SHA} \
            ghcr.io/cosmo-tech/cosmotech-api:latest
          docker image push ghcr.io/cosmo-tech/cosmotech-api:latest

  push_helm_charts_to_oci_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      # OCI Support by Helm is considered experimental
      HELM_EXPERIMENTAL_OCI: 1

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Helm
        uses: azure/setup-helm@v1.1
        with:
          version: v3.6.0

      - name: Retrieve branch or tag name
        id: refvar
        run: echo "::set-output name=gitRefName::${GITHUB_REF#refs/*/}"

      - name: Login to GitHub Container Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | \
            helm registry login ghcr.io \
              --username "${{ github.actor }}" \
              --password-stdin

      - name: Push API Helm Chart (tag) to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          helm chart save api/kubernetes/helm-chart/ ghcr.io/cosmo-tech/cosmotech-api-chart:${{ steps.refvar.outputs.gitRefName }}
          helm chart push ghcr.io/cosmo-tech/cosmotech-api-chart:${{ steps.refvar.outputs.gitRefName }}

      - name: Push API Helm Chart (latest) to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          helm chart save api/kubernetes/helm-chart/ ghcr.io/cosmo-tech/cosmotech-api-chart:latest
          helm chart push ghcr.io/cosmo-tech/cosmotech-api-chart:latest

      - name: Push csm-argo Helm Chart (tag) to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          helm dependency update api/kubernetes/csm-argo/
          helm chart save api/kubernetes/csm-argo/ ghcr.io/cosmo-tech/csm-argo-chart:${{ steps.refvar.outputs.gitRefName }}
          helm chart push ghcr.io/cosmo-tech/csm-argo-chart:${{ steps.refvar.outputs.gitRefName }}

      - name: Push csm-argo Helm Chart (latest) to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          helm dependency update api/kubernetes/csm-argo/
          helm chart save api/kubernetes/csm-argo/ ghcr.io/cosmo-tech/csm-argo-chart:latest
          helm chart push ghcr.io/cosmo-tech/csm-argo-chart:latest

      - name: Logout from GitHub Container Registry
        if: ${{ always() }}
        run: |
          helm registry logout ghcr.io || true
