name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:

  push_container_images_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      DOCKER_BUILDKIT: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'

      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Retrieve branch or tag name
        id: refvar
        run: echo "::set-output name=gitRefName::${GITHUB_REF#refs/*/}"

      # TODO Commented out until we find a better strategy to authenticate without Docker Hub PATs
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#
#      - name: Push API Container Image (tag) to Docker Hub
#        if: startsWith(github.ref, 'refs/tags/')
#        run: |
#          ./gradlew :cosmotech-api:jib \
#            -Djib.to.image="registry.hub.docker.com/cosmotech/cosmotech-api:${{ steps.refvar.outputs.gitRefName }}"
#
#      - name: Push API Container Image (latest) to Docker Hub
#        if: github.ref == 'refs/heads/main'
#        run: |
#          ./gradlew :cosmotech-api:jib \
#            -Djib.to.image="registry.hub.docker.com/cosmotech/cosmotech-api:latest"

      - name: Push API Container Image (tag) to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew :cosmotech-api:jib \
            -Djib.to.image="ghcr.io/cosmotech/cosmotech-api:${{ steps.refvar.outputs.gitRefName }}" \
            -Djib.to.auth.username="${{ github.actor }}" \
            -Djib.to.auth.password="${GITHUB_TOKEN}"

      - name: Push API Container Image (latest) to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew :cosmotech-api:jib \
            -Djib.to.image="ghcr.io/cosmotech/cosmotech-api:latest" \
            -Djib.to.auth.username="${{ github.actor }}" \
            -Djib.to.auth.password="${GITHUB_TOKEN}"
