# See https://docs.kubelinter.io/#/configuring-kubelinter?id=configuring-kubelinter
checks:
  # run all built-in checks
  addAllBuiltIn: true

  # include explicitly adds checks, by name. You can reference any of the built-in checks.
  # Note that customChecks defined above are included automatically.
  include: []
  # exclude explicitly excludes checks, by name. exclude has the highest priority: if a check is
  # in exclude, then it is not considered, even if it is in include as well.
  exclude:
    - use-namespace

## customChecks defines custom checks.
#customChecks:
#  - name: "required-annotation-team"
#    template: "required-annotation"
#    params:
#      key: "team"
#    remediation: "Add a team annotation to your object"
