openapi: 3.0.3

info:
  title: ""
  version: ""

security:
  - oAuth2AuthCode: []

tags:
- name: connector
  description: Connector Management

paths:
  /connectors:
    post:
      operationId: registerConnector
      tags:
        - connector
      summary: Register a new connector
      requestBody:
        description: the Connector to register
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Connector'
            examples:
              ADTConnector:
                $ref: '#/components/examples/ADTConnector'
          application/yaml:
            schema:
              $ref: '#/components/schemas/Connector'
            examples:
              ADTConnector:
                $ref: '#/components/examples/ADTConnector'
      responses:
        "201":
          description: the connector details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connector'
              examples:
                ADTConnector:
                  $ref: '#/components/examples/ADTConnector'
            application/yaml:
              schema:
                $ref: '#/components/schemas/Connector'
              examples:
                ADTConnector:
                  $ref: '#/components/examples/ADTConnector'
        "400":
          description: Bad request
    get:
      operationId: findAllConnectors
      tags:
        - connector
      parameters:
        - name: page
          in: query
          description: page number to query (first page is at index 0)
          required: false
          schema:
            type: integer
        - name: size
          in: query
          description: amount of result by page
          required: false
          schema:
            type: integer
      summary: List all Connectors
      responses:
        "200":
          description: the list of Connectors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connector'
              examples:
                OneConnector:
                  $ref: '#/components/examples/OneConnector'
            application/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Connector'
              examples:
                OneConnector:
                  $ref: '#/components/examples/OneConnector'

  /connectors/{connector_id}:
    parameters:
      - name: connector_id
        in: path
        description: the Connector identifier
        required: true
        schema:
          type: string
    get:
      operationId: findConnectorById
      tags:
        - connector
      summary: Get the details of a connector
      responses:
        "200":
          description: the Connector details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connector'
              examples:
                ADTConnector:
                  $ref: '#/components/examples/ADTConnector'
            application/yaml:
              schema:
                $ref: '#/components/schemas/Connector'
              examples:
                ADTConnector:
                  $ref: '#/components/examples/ADTConnector'
        "404":
          description: the Connector specified is unknown or you don't have access to it
    delete:
      operationId: unregisterConnector
      tags:
        - connector
      summary: Unregister a connector
      responses:
        "204":
          description: Request successful
        "404":
          description: the Connector specified is unknown or you don't have access to it

components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: "https://example.com/authorize"
          tokenUrl: "https://example.com/token"
          scopes: {}
  schemas:
    Connector:
      type: object
      x-class-extra-annotation: "@com.redis.om.spring.annotations.Document"
      description: a version of a Connector
      properties:
        id:
          type: string
          x-field-extra-annotation: "@org.springframework.data.annotation.Id"
          readOnly: true
          description: the Connector version unique identifier
        key:
          type: string
          description: the Connector key which group Connector versions
        name:
          type: string
          x-field-extra-annotation: "@com.redis.om.spring.annotations.Searchable"
          description: the Connector name
        description:
          type: string
          description: the Connector description
        repository:
          type: string
          description: the registry repository containing the image
        version:
          type: string
          description: the Connector version MAJOR.MINOR.PATCH. Must be aligned with an existing repository tag
        tags:
          type: array
          description: the list of tags
          items:
            type: string
        ownerId:
          type: string
          readOnly: true
          description: the user id which own this connector version
        url:
          type: string
          description: an optional URL link to connector page
        ioTypes:
          type: array
          items:
            $ref: '#/components/schemas/ioTypesEnum'
        parameterGroups:
          type: array
          description: the list of connector parameters groups
          items:
            $ref: '#/components/schemas/ConnectorParameterGroup'
    ioTypesEnum:
      type: string
      description: The read and write capabilities of connector
      enum:
        - read
        - write
    ConnectorParameterGroup:
      type: object
      description: a connector parameters group
      properties:
        id:
          type: string
          description: the connector parameter group id
        label:
          type: string
          description: the list of translated parameter group labels
        parameters:
          type: array
          description: the list of parameters
          items:
            $ref: '#/components/schemas/ConnectorParameter'
      required:
        - id
        - label
        - parameters
    ConnectorParameter:
      type: object
      description: a connector parameter
      properties:
        id:
          type: string
          description: the connector parameter id
        label:
          type: string
          description: the list of translated parameter group labels
        valueType:
          type: string
          description: the parameter value type
        options:
          type: array
          description: the list of available and valid values for the parameter
          items:
            type: string
        default:
          type: string
          description: the default value
        envVar:
          type: string
          description: associated environment variable in connector image
      required:
        - id
        - label
  examples:
    ADTConnector:
      summary: ADT Connector
      description: ADT Connector example
      value:
        id: "1"
        key: ADT Connector
        name: ADT Connector
        description: Connector for Azure Digital Twins. Read ADT and write the data in CSV for a ScenarioRun
        repository: azure-digital-twins-simulator-connector
        version: "1.0.0"
        tags:
          - ADT
        ownerId: "1"
        url: https://github.com/Cosmo-Tech/azure-digital-twins-simulator-connector
        ioTypes:
          - read
        parameterGroups:
          - id: security
            label: Security
            parameters:
              - id: AZURE_TENANT_ID
                label: Azure Tenant Id
                valueType: string
                envVar: AZURE_TENANT_ID
              - id: AZURE_CLIENT_ID
                label: Azure Client Id
                valueType: string
                envVar: AZURE_CLIENT_ID
              - id: AZURE_CLIENT_SECRET
                label: Azure CLient secret
                valueType: password
                envVar: AZURE_CLIENT_SECRET
          - id: parameters
            label: Parameters
            parameters:
              - id: AZURE_DIGITAL_TWINS_URL
                label: Azure Digital Twins URL
                valueType: string
                envVar: AZURE_DIGITAL_TWINS_URL
              - id: ADT_QUERY
                label: Azure Digital Twins query
                valueType: string
                envVar: AZURE_DIGITAL_TWINS_QUERY
                default: SELECT * FROM digitaltwins
              - id: EXPORT_CSV_FILE_ABSOLUTE_PATH
                label: CSV file export absolute path
                valueType: string
                default: /mnt/scenariorun-data
                envVar: EXPORT_CSV_FILE_ABSOLUTE_PATH
    OneConnector:
      summary: One Connector list
      description: One Connector list example
      value:
        - id: "1"
          key: ADT Connector
          name: ADT Connector
          description: Connector for Azure Digital Twins. Read ADT and write the data in CSV for a ScenarioRun
          repository: azure-digital-twins-simulator-connector
          version: "1.0.0"
          tags:
            - ADT
          ownerId: "1"
          url: https://github.com/Cosmo-Tech/azure-digital-twins-simulator-connector
          ioTypes:
            - read
          parameterGroups:
            - id: security
              label: Security
              parameters:
                - id: AZURE_TENANT_ID
                  label: Azure Tenant Id
                  valueType: string
                  envVar: AZURE_TENANT_ID
                - id: AZURE_CLIENT_ID
                  label: Azure Client Id
                  valueType: string
                  envVar: AZURE_CLIENT_ID
                - id: AZURE_CLIENT_SECRET
                  label: Azure CLient secret
                  valueType: password
                  envVar: AZURE_CLIENT_SECRET
            - id: parameters
              label: Parameters
              parameters:
                - id: AZURE_DIGITAL_TWINS_URL
                  label: Azure Digital Twins URL
                  valueType: string
                  envVar: AZURE_DIGITAL_TWINS_URL
                - id: ADT_QUERY
                  label: Azure Digital Twins query
                  valueType: string
                  envVar: AZURE_DIGITAL_TWINS_QUERY
                  default: SELECT * FROM digitaltwins
                - id: EXPORT_CSV_FILE_ABSOLUTE_PATH
                  label: CSV file export absolute path
                  valueType: string
                  default: /mnt/scenariorun-data
                  envVar: EXPORT_CSV_FILE_ABSOLUTE_PATH
