openapi: 3.0.3

info:
  title: "Cosmotech Connector API"
  version: "3.0.0"
  description: "Cosmotech Connector API"

security:
  - oAuth2AuthCode: []

tags:
- name: connector
  description: Connector Management

paths:
  /connectors:
    $ref: './paths/connector.yaml#/paths/connectors'
  '/connectors/{connector_id}':
    $ref: './paths/connector.yaml#/paths/connectors/{connector_id}'

components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: "https://example.com/authorize"
          tokenUrl: "https://example.com/token"
          scopes: {}
  schemas:
    Connector:
      $ref: './schemas/connector.yaml#/Connector'
    ioTypesEnum:
      $ref: './schemas/connector.yaml#/ioTypesEnum'
    ConnectorParameterGroup:
      $ref: './schemas/connector.yaml#/ConnectorParameterGroup'
    ConnectorParameter:
      $ref: './schemas/connector.yaml#/ConnectorParameter'
  examples:
    ADTConnectorRequest:
      $ref: './examples/connector.yaml#/ADTConnectorRequest'
    ADTConnectorResponse:
      $ref: './examples/connector.yaml#/ADTConnectorResponse'
    ConnectorListResponse:
      $ref: './examples/connector.yaml#/ConnectorListResponse'
