openapi: 3.0.3

info:
  title: ""
  version: ""

security:
  - oAuth2AuthCode: []

tags:
- name: connector
  description: Connector Management

paths:
  $ref: './paths/connector.yaml#/'

components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: "https://example.com/authorize"
          tokenUrl: "https://example.com/token"
          scopes: {}
  schemas:
    $ref: './schemas/connector.yaml#/components/schemas'
  examples:
    $ref: './examples/connector.yaml#/components/examples'
